### ISSUE TITLE
Update list of OPS fulltext countries

### ISSUE THREAD

**Issue by amotl** [ip-tools/patzilla#50]
Dear @aghster,

thank you again for your contribution #3 submitted the other day. In the OPS manual 1.3.16 [^1], I observed the following change log items since I've looked at it the last time:

- 2019-05-07 1.3.10 Updated fulltext collection.
- 2019-09-05 1.3.15 Updated the fulltext country code list.
- 2020-09-14 1.3.16 Correction to countries list.

Maybe it is not too difficult to figure out what has changed here, and converge that into a patch, if necessary.

With kind regards,
Andreas.

[^1]: https://documents.epo.org/projects/babylon/eponet.nsf/0/F3ECDCC915C9BCD8C1258060003AA712/$File/ops_v3.2_documentation_-_version_1.3.16_en.pdf

**Comment by aghster** [comment]
This may be the list you are looking for: https://www.epo.org/searching-for-patents/data/web-services/ops/faq.html#faq-74

**Comment by amotl** [comment]
Thank you very much. ccc50d9 will bring the list up to speed.
