### ISSUE TITLE
User interface is broken when displaying document details

### ISSUE THREAD

**Issue by amotl** [ip-tools/patzilla#69]
Hi there,

when starting PatZilla in development/sandbox mode, I am observing a few glitches.

First, something is wrong with the fonts on the data source chooser.
![image](https://user-images.githubusercontent.com/453543/227718692-be888940-7a77-42c8-a00a-3d6296cf7a58.png)

Then, as already discovered and reported by @papoteur-mga at https://github.com/ip-tools/patzilla/issues/68#issuecomment-1483764413, it looks like the document details are not displayed at all, and, in the same manner, the document details chooser also does not work. The problem can easily be revealed by conducting a simple query.

![image](https://user-images.githubusercontent.com/453543/227718568-4531faed-cd00-4aef-850d-b64895f87467.png)
![image](https://user-images.githubusercontent.com/453543/227718575-7c8a0bbc-26b3-40a5-895e-858a2775e8e6.png)

Bummer! I will try to look into this on the weekend, or next week.

With kind regards,
Andreas.

**Comment by amotl** [comment]
I can confirm everything works well on the hosted instance at https://patzilla.ip-tools.io/. Hopefully, the problem will not be a big thing.

![image](https://user-images.githubusercontent.com/453543/227718810-a2399ed1-8992-4be5-8a06-cfa900eca834.png)

**Comment by amotl** [comment]
Do you observe the very same problems, @papoteur-mga? Or do you actually see result details, and only the Biblio/Claims/Desc/Family chooser does not work?

**Comment by amotl** [comment]
0933634524 fixes the problem on my end. Please let me know if you see any other errors related to this.

**Comment by papoteur-mga** [comment]
> Do you observe the very same problems, @papoteur-mga? Or do you actually see result details, and only the Biblio/Claims/Desc/Family chooser does not work?

This is what I see, when I have one document found.
But the commit doesn't change the result for me :(

**Comment by amotl** [comment]
> The commit doesn't change the result for me :(

Did you rebuild the JavaScript/frontend bundle?

**Comment by amotl** [comment]
Have to leave _now_. Apologies. See you tomorrow.

**Comment by papoteur-mga** [comment]
Ah, yes, indeed, rebuild was needed.
It works !

**Comment by amotl** [comment]
Excellent. Enjoy your research!

On 25 March 2023 16:48:54 CET, Papoteur ***@***.***> wrote:
>Ah, yes, indeed, rebuild was needed.
>It works !
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ip-tools/patzilla/issues/69#issuecomment-1483855047
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
-- 
Sent from my mind. This might have been typed on a mobile device, so please excuse my brevity.

**Comment by amotl** [comment]
May I ask if you also see the bogus font rendering on the data source chooser component, as displayed in my first post?

**Comment by papoteur-mga** [comment]
> May I ask if you also see the bogus font rendering on the data source chooser component?
> 
> ![image](https://user-images.githubusercontent.com/453543/227718692-be888940-7a77-42c8-a00a-3d6296cf7a58.png)

Yes, I have the same.

**Comment by amotl** [comment]
Thanks. 9f697b5b3d fixes this glitch.
